### ISSUE TITLE
crossbows can deal damage in towns 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTownsDocs#14]
Crossbows appear to still inflict damage in a Town, with or without a combat plugin or state being enabled or disabled.

**Comment by WiIIiam278** [comment]
Can this be verified?

**Comment by Iotados** [comment]
Will verify asap; will be using a bedrock and java account to verify but original report was with 2 java players so should not make a difference

**Comment by Iotados** [comment]
bug dismissed; false report
