### ISSUE TITLE
Reported: Dynmap no longer shows claims

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTownsDocs#23]
Reported by GrandpaCrunkle#3763
> Also it seems with 1.17 that the claims for Dynmap no longer appear on the map

Can not confirm or test as no HuskTowns jar is available for use.

**Comment by WiIIiam278** [comment]
Confirmed, looks like the new Dynmap doesn't support the API version. Bumped API to 3.1-beta-2 which is now compatible.
