### ISSUE TITLE
Town Flag System

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTownsDocs#31]
>Add a /flags or /town flags, so that leaders can deactivate certain options in their town, for example pvp, explosions, friendly fire, >etc.
Original Suggestion by **Syndr4**

Town Flags and Admin Flags should be done seperate

**Comment by Iotados** [comment]
This has been extended in the RoadMap. Please see that before making any suggestions or comments, found under the wiki/RoadMap section [or by clicking here](https://github.com/WiIIiam278/HuskTownsDocs/wiki/Roadmap)

**Comment by Iotados** [comment]
Pinned:

Heya Folks,
If you have suggestions for Flags. Please inform us, we can see if they would fit the system, if there possible and if they would follow the preamble set forth in the Roadmap.

**Comment by WiIIiam278** [comment]
Feature complete for 1.5
