### ISSUE TITLE
PVP flag false-checking issue 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTownsDocs#45]
Throwing an enderpearl inside a claim with pvp disabled still throws the "PvP is disabled..." message even if no player is present or hit.

**Comment by Iotados** [comment]
Fastest issue open to close ratio so far... seconds later and the update to fix it launches!

**Comment by WiIIiam278** [comment]
![image](https://user-images.githubusercontent.com/31187453/129493784-14d1c044-dfc2-4f7a-8b79-13e826ae4236.png)
Already done, a few seconds too slow!

**Comment by Iotados** [comment]
Smh
