### ISSUE TITLE
Distinguish chunk types on Map by Symbols 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTownsDocs#5]
Distinguish chunk types (Farm, Plot, Player Location etc.) by Symbols on the map, allowing for better visibility. 
This should probably be toggle-able in some way or modifiable for what would show.

**Comment by WiIIiam278** [comment]
Should add additional config options letting server owners customize how the map looks

**Comment by WiIIiam278** [comment]
Problem with this as I see it is that using any other unicode characters than the defaults would ruin the spacing. I'm going to close this for now unless there's more demand, however 1.4 does have a setting letting users control the size of the map.
